version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      actions:
        patterns: ["*"]

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      dev-deps:
        dependency-type: "development"
        patterns: ["*"]
    ignore:
      - dependency-name: "leaflet"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      runtime-deps:
        dependency-type: "production"
        patterns: ["*"]
